### PR TITLE
rpm: implement shared library packaging guideline

### PR DESCRIPTION
**Pull request by jengelh**
SR 530107 from the OBS + a bit.

### CODE REVIEW

**Comment by gonzoleeman** [comment]
Can I assume you've tested these changes in OBS? If so, they seem fine to me.

**Comment by jengelh** [comment]
Local build via `osc build` with updates .spec succeeded when I tried.

**Comment by gonzoleeman** [comment]
I am looking at your changes closely now. I will try them with the build service myself.

But it looks like there's a missing dependency? Shouldn't the top-level open-iscsi package require the new library, as does the "devel" package?  Adding something like this to the spec file:

```
--- open-iscsi.spec.orig        2018-02-08 11:33:17.492824029 -0800
+++ open-iscsi.spec     2018-02-08 11:33:47.081671011 -0800
@@ -39,6 +39,7 @@ BuildRequires:  open-isns-devel
 BuildRequires:  openssl-devel
 BuildRequires:  suse-module-tools
 BuildRequires:  systemd
+Requires:       libopeniscsiusr0 = %{version}
 Requires(post): coreutils
 %{?systemd_requires}
```
Otherwise, loading the open-iscsi package will not load the libopeniscsiusr package, right?

**Comment by jengelh** [comment]
>Shouldn't the top-level open-iscsi package require the new library, as does the "devel" package?

rpm does that on its own, always has been.

**Comment by gonzoleeman** [comment]
I am looking at your changes closely now. I will try them with the build service myself.

But it looks like there's a missing dependency? Shouldn't the top-level open-iscsi package require the new library, as does the "devel" package?  Adding something like this to the spec file:

```
--- open-iscsi.spec.orig        2018-02-08 11:33:17.492824029 -0800
+++ open-iscsi.spec     2018-02-08 11:33:47.081671011 -0800
@@ -39,6 +39,7 @@ BuildRequires:  open-isns-devel
 BuildRequires:  openssl-devel
 BuildRequires:  suse-module-tools
 BuildRequires:  systemd
+Requires:       libopeniscsiusr0 = %{version}
 Requires(post): coreutils
 %{?systemd_requires}
```
Otherwise, loading the open-iscsi package will not load the libopeniscsiusr package, right?

**Comment by gonzoleeman** [comment]
Okay, after more testing, it looks like the RPMs don't in general "Require:" the packages of the libraries it uses, so I remove my objection.

**Comment by gonzoleeman** [comment]
Thank you!

**Pull request merged**
